name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['7.5.1804', '8.3.2011']

    container: centos:${{ matrix.tag }}

    steps:
      - run: yum -y update && yum -y install git file
        if:  ${{ matrix.tag == '7.5.1804' }}

      - run: dnf -y update && dnf -y install git file
        if:  ${{ matrix.tag == '8.3.2011' }}

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags

      - run: ./autogen.sh --help
      - run: ./autogen.sh -h
      - run: ./autogen.sh -V
      - run: ./autogen.sh --version
      - run: ./autogen.sh env
      - run: ./autogen.sh integrate zsh
      - run: ./autogen.sh upgrade

      - run: cd ctags && ./autogen.sh configure

      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version

  test_6_10:
    runs-on: ubuntu-20.04

    container: centos:6.10

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-Base.repo

      - run: yum -y update
      - run: yum -y install file curl xz

      - run: |
          curl -LO https://github.com/leleliu008/git-prebuild/releases/download/2.30.2/git-2.30.2-x86_64-linux-glibc.tar.xz
          tar xf git-2.30.2-x86_64-linux-glibc.tar.xz -C /opt
          ln -sf /opt/git-2.30.2-x86_64-linux-glibc/bin/git /usr/bin/git

      - run: git --version

      - run: git init
      - run: git remote add origin https://github.com/${{github.repository}}
      - run: git config --local gc.auto 0
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +${{github.sha}}:refs/remotes/origin/master
      - run: git checkout --progress --force -B master refs/remotes/origin/master
      - run: ls

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags

      - run: ./autogen.sh --help
      - run: ./autogen.sh -h
      - run: ./autogen.sh -V
      - run: ./autogen.sh --version
      - run: ./autogen.sh env
      - run: ./autogen.sh integrate zsh
      - run: ./autogen.sh upgrade

      - run: cd ctags && ./autogen.sh configure -x

      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
