name: LinuxMint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [19.3, 20.1]

    container: linuxmintd/mint${{ matrix.tag }}-amd64

    steps:
      - run: apt -y update
      - run: apt -y install git file

      - uses: actions/checkout@v2

      - run: git clone https://github.com/universal-ctags/ctags

      - run: cp autogen.sh ctags
      - run: cp autogen.rc ctags

      - run: ./autogen.sh --help
      - run: ./autogen.sh -h
      - run: ./autogen.sh -V
      - run: ./autogen.sh --version
      - run: ./autogen.sh env
      - run: ./autogen.sh integrate zsh
      - run: ./autogen.sh upgrade

      - run: cd ctags && ./autogen.sh configure

      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version
