name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15
    
    strategy:
      matrix:
        version: [8, 9]

    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/netbsd${{ matrix.version }}
        run: |
          run sudo pkgin -y install git mozilla-rootcerts

          run sudo mozilla-rootcerts install

          run git clone https://github.com/universal-ctags/ctags

          run cp autogen.sh ctags
          run cp autogen.rc ctags

          run ./autogen.sh --help
          run ./autogen.sh -h
          run ./autogen.sh -V
          run ./autogen.sh --version
          run ./autogen.sh env
          run ./autogen.sh integrate zsh
          run ./autogen.sh upgrade

          run cd ctags
          run ./autogen.sh configure
          run ./configure --prefix=/usr
          run make
          run sudo make install
          run file /usr/bin/ctags
          run /usr/bin/ctags --version
